### ISSUE TITLE
Add rules 

### ISSUE THREAD

**Issue by seanc** [JustDame/Connect4#37]
Some rules and instructions should be added above the board.

Instructions:
1. Click the blue "Reset" button below the board on the left to reset the board. You will KEEP your wins, losses, and ties.
2. Click on the red "Quit" button below the board on the right to reset the board. You will LOSE your wins, losses, and ties.
3. To place a piece, click above the column you want to place your chip in. The closest available spot to the bottom of the board will be taken.
4. You are the RED chip.
5. You can only win by getting 4 of your chips in a row. Horizontal and diagonal winning is not yet implemented.

**Comment by seanc** [comment]
@Jordane-Allen brought up a great suggestion about using a materializecss modal for displaying the rules. I think this would be great because we only have so much space to use before it becomes obtrusive to the user since the board is pushed further down the page. 

Here is documentation on how to create modals: https://materializecss.com/modals.html#!

Another consideration also would be to show this when the user visits the page and also make it viewable by clicking a button too.

**Comment by Jade-Marte** [comment]
rules look good
